### ISSUE TITLE
Handling Cache Shutdown

### ISSUE THREAD

**Issue by ryan-buckman** [wislon/xam-akavache-test#1]
Is calling `SharedAppGlobal.NormalCache.Shutdown.Wait();` via the `override void OnSleep()` the correct way to Shutdown the cache in Xamarin Forms? When i try this it never seems to complete.

Thanks

**Comment by wislon** [comment]
@ryan-buckman to be honest, I'm not a hundred percent sure that OnSleep is the best place for it...

This may be a dumb question, but have you tried 

`Task.Run(async () => await SharedAppGlobal.blah())` (drop the `.Wait()` )? 

You don't really care about the result, since you're shutting down anyway...

Then just do a test run to see if it persisted everything you needed it to?
